name: app
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
  sdk: ">=2.18.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.5
  animated_splash_screen: ^1.1.0
  hive: null
  hive_flutter: null
  sqflite: any
  path_provider: any
  flutter_slidable: any
  image_picker: ^0.8.6
  flutter_barcode_scanner: ^2.0.0
  provider: ^4.0.4
  intl: ^0.17.0
  dropdown_button2: ^1.8.9
  autocomplete_textfield: ^2.0.1
  flutter_typeahead: ^4.1.1
  internet_connection_checker: ^1.0.0+1
  multi_trigger_autocomplete: ^0.1.1
  socket_io_client: ^2.0.0
  dart_ping: ^7.0.2
  flutter_easyloading: ^3.0.5
  fab_circular_menu: ^1.0.2
  persistent_bottom_nav_bar: ^5.0.2
  google_nav_bar: ^5.0.6
  rflutter_alert: ^2.0.4
  modal_bottom_sheet: ^2.1.2
  draggable_fab: ^0.1.4
  draggable_expandable_fab: ^1.0.0
  badges: ^2.0.3
  get: any
  synchronized: ^3.0.0+3
  tip_dialog: ^4.0.0
  top_snackbar_flutter: ^3.0.0
  m_toast: ^0.1.8
  another_flushbar: ^1.12.29
  flutter_native_splash: ^2.2.16
  multilevel_drawer: ^2.0.0
  awesome_dialog: ^3.0.2
  date_picker_timeline: ^1.2.3
  convex_bottom_bar: ^3.1.0+1
  flutter_statusbarcolor_ns: ^0.5.0
  # flutter_speed_dial: ^6.2.0
  flutter_launcher_icons: ^0.11.0
  flash: ^2.0.5
  flutter_dropdown_alert: ^1.0.6
  awesome_snackbar_content: ^0.1.0
  line_icons: ^2.0.1
  font_awesome_flutter: ^10.3.0

flutter_icons:
  android: true
  ios: true
  image_path: "lib/assets/images/logo-social.png"

flutter_native_splash:
  image: lib/assets/images/logo-social.png
  color: "#fafafa"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - lib\assets\images\logo-social.png

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
